# Implementation of Neural network : feed forward and backpropogation

In [1]:
import numpy as np
X = np.array(([2,9], [1,5], [3,6]), dtype = float)
y = np.array(([92], [86], [89]), dtype = float)

In [2]:
print(X)

[[2. 9.]
 [1. 5.]
 [3. 6.]]


In [3]:
print(y)

[[92.]
 [86.]
 [89.]]


#### scale units

In [4]:
# maximum of x array
X = X/np.amax(X, axis = 0)
print(X)

# maximum of test
y = y/100
print(y)

[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
[[0.92]
 [0.86]
 [0.89]]


In [6]:
class NeuralNetwork(object):
    
    def __init__(self):
        
        # parameters
        self.inputSize = 2
        self.outputSize = 1
        self.hiddenSize = 3
        
        #weights
        # (3x2) weight matrix from input to hidden layer
        self.w1 = np.random.randn(self.inputSize, self.hiddenSize)
        
        # (3x1) weight matrix from hidden to output layer
        self.w2 = np.random.randn(self.hiddenSize, self.outputSize)
        
        
    # forward propagation through network
    def forward(self, X):
        
        # dot prod of X and first set of weights
        self.z = np.dot(X, self.w1)
        
        # activation function
        self.z2 = self.sigmoid(self.z)
        
        # dot production hidden layer to select set of weights
        self.z3 = np.dot(self.z2, self.w2)
        
        # final activation
        o = self.sigmoid(self.z3)
        
        return o
        

    # activation function
    def sigmoid(self, s):
        return (1/(1 + np.exp(-s)))
    
    
    # derivative of sigmoid
    def sigmoidPrime(self, s):
        return (s*(1-s))
    
    
    # backward propagation through the network
    def backward(self, X, y, o):
        
        # error in output
        self.o_error = y - o
        
        # applying derivative
        self.o_delta = self.o_error*self.sigmoidPrime(o)
        
        # z2 error : how much our hidden layer contribute
        self.z2_error = self.o_delta.dot(self.w2.T)
        
        # applying derivative again
        self.z2_delta = self.z2_error*self.sigmoidPrime(self.z2)
        
        # adjusting first set
        self.w1 += X.T.dot(self.z2_delta)
        
        # adjusting second set
        self.w2 += self.z2.T.dot(self.o_delta)
        
        
    def train(self, X, y):
        o = self.forward(X)
        self.backward(X,y,o)
    
NN = NeuralNetwork()
for i in range(100):
    print("Input \n" + str(X))
    print("Actual output : \n" + str(y))
    print("Predicted output : \n" + str(NN.forward(X)))
    print("Loss" + str(np.mean(np.square(y-NN.forward(X)))))
    print("\n")
    NN.train(X, y)

Input 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual output : 
[[0.92]
 [0.86]
 [0.89]]
Predicted output : 
[[0.47818252]
 [0.50765688]
 [0.44163757]]
Loss0.1734590765785334


Input 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual output : 
[[0.92]
 [0.86]
 [0.89]]
Predicted output : 
[[0.51709058]
 [0.54755421]
 [0.4748377 ]]
Loss0.14410603546879244


Input 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual output : 
[[0.92]
 [0.86]
 [0.89]]
Predicted output : 
[[0.55164094]
 [0.58284608]
 [0.50428197]]
Loss0.12042703184360792


Input 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual output : 
[[0.92]
 [0.86]
 [0.89]]
Predicted output : 
[[0.58254367]
 [0.61404898]
 [0.53073235]]
Loss0.10114730705779307


Input 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual output : 
[[0.92]
 [0.86]
 [0.89]]
Predicted output : 


Predicted output : 
[[0.88921535]
 [0.89129907]
 [0.8437344 ]]
Loss0.0013559442720434262


Input 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual output : 
[[0.92]
 [0.86]
 [0.89]]
Predicted output : 
[[0.8897928 ]
 [0.8917898 ]
 [0.84451467]]
Loss0.001330660463711522


Input 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual output : 
[[0.92]
 [0.86]
 [0.89]]
Predicted output : 
[[0.89034713]
 [0.89226052]
 [0.84526578]]
Loss0.0013070614721008992


Input 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual output : 
[[0.92]
 [0.86]
 [0.89]]
Predicted output : 
[[0.89087948]
 [0.89271221]
 [0.84598912]]
Loss0.001285017013917756


Input 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual output : 
[[0.92]
 [0.86]
 [0.89]]
Predicted output : 
[[0.89139095]
 [0.89314581]
 [0.84668601]]
Loss0.0012644081608168204


Input 
[[0.66666667 1.        ]
 [0.33333333 0.