# Numpy Library in Python:
---------------------------------------------------

In [3]:
from IPython.display import Image
Image(url= "https://miro.medium.com/max/672/1*L9bMlmBcLi6L-B6zNvwKBw.png")

**1D array**

In [1]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [2]:
type(arr)

numpy.ndarray

In [3]:
print(type(arr))

<class 'numpy.ndarray'>


**2D array**

In [4]:
arr1 = np.array([[1,2,3,4],[2,3,4,5]])
print(arr1)

[[1 2 3 4]
 [2 3 4 5]]


In [5]:
print(arr1[0][3])

4


**shape and size**

find the size and shape of the array using ‘size’ and ‘shape’ function respectively.

In [6]:
arr.shape
#since arr is 1D array so there is only 4 rows with no columns

(4,)

In [7]:
arr1.shape
#arr1 is 2D array so it has 2 rows and 4 columns

(2, 4)

In [20]:
a = np.array([(1,2,3,4,5,6)])
a1 = np.array([(1,2,3,3),(4,5,6,4)])
print(a1)
print(a1.size)
print(a1.shape)

[[1 2 3 3]
 [4 5 6 4]]
8
(2, 4)


**ndim**

In [8]:
arr.ndim
#dim stands for dimension
#so here arr is 1-D array

1

In [9]:
arr1.ndim
#it tells us that it is 2-D array

2

In [14]:
a = np.array([(1,2,3),(4,5,6)])
a1 = np.array([((1,2,3),(4,5,6)),((1,2,3),(4,5,6))])
print(a.ndim)
print(a1.ndim)

2
3


**reshape**

In [10]:
arr2 = np.array([[1,3],[2,3],[4,6]])
arr2.shape
#2D array with 3 rows and 2 columns

(3, 2)

Here 3 * 2 = 6 , so there are 6 elements in this 2D array. so we reshape this 2D array in which only 6 elements exist such as (2,3) ,(6,1),(1,6). but not in (2,2) ,(3,5).

In [15]:
arr2.reshape(2,3)

array([[1, 3, 2],
       [3, 4, 6]])

In [5]:
arr2.reshape(6,1)

array([[1],
       [3],
       [2],
       [3],
       [4],
       [6]])

In [6]:
arr2.reshape(1,6)

array([[1, 3, 2, 3, 4, 6]])

In [7]:
arr2.reshape(3,5)
# becoz there would be 3 * 5 = 15 elements

ValueError: cannot reshape array of size 6 into shape (3,5)

**itemsize**

In [19]:
# calculate the byte size of each element
a = np.array([(1,2,3)])
print(a.itemsize)

4


**dtype**

find the data type of the elements that are stored in anarray. So, if you want to know the data type of a particular element, you can use‘dtype’ function which will print the data type along with the size.

In [10]:
a = np.array([(1,2,3)])
print(a.dtype)

int32


**arange**

In [10]:
new = np.arange(5)
# we can only make 1D array with this function .
# to make 2D array we have to reshape it.

In [18]:
print(new)

[0 1 2 3 4]


In [11]:
np.arange(1,10,2)
# all numbers b/w 1(including) to 10(excluding) with increment of 2

array([1, 3, 5, 7, 9])

In [3]:
np.arange(7, 0, -3)

array([7, 4, 1])

In [12]:
np.arange?
# this give all the details about the arange function 

In [4]:
np.arange(1,10.1,3)

array([ 1.,  4.,  7., 10.])

In [13]:
x = np.arange(5)
print(x)
print(x.dtype)
print(x.itemsize) 
# itemsize means length of one array element in bytes.

[0 1 2 3 4]
int32
4


In [6]:
x = np.arange(1, 5.0, 0.25)
print(x)
print(x.dtype)
print(x.itemsize)

[1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.   3.25 3.5  3.75 4.   4.25
 4.5  4.75]
float64
8


In [8]:
#empty numpy array using arange
print(np.arange(0))
np.arange(2,2)
np.arange(8,2,1)
np.arange(2,8,-1)

[]


array([], dtype=int32)

In [23]:
#Create a vector with values ranging from 10 to 49
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [7]:
#Create a 3x3 matrix with values ranging from 0 to 8
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [8]:
#Reverse a vector (first element becomes last)
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


**converting int data types into float**

In [9]:
arr3 = np.array([[1,3],[2,3],[4,6]],dtype = float)

In [11]:
print(arr3)

[[1. 3.]
 [2. 3.]
 [4. 6.]]


**pi**

In [12]:
np.pi
#printing the pi value

3.141592653589793

**np.Zeros()**

this function will create an array (either 1D or 2D according to the parameters we provide) with zeros and by default data type is float

In [15]:
z = np.zeros(3)
z

array([0., 0., 0.])

In [14]:
z = np.zeros((3,2))
z

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [30]:
z = np.zeros((3,2),dtype = object)
z

array([[0, 0],
       [0, 0],
       [0, 0]], dtype=object)

In [22]:
print(np.nonzero([1,2,0,0,4,0])) #Compute the indices of the elements that are non-zero
print(np.zeros(10)) #null vector of size 10
#null vector of size 10 but the fifth value which is 1
Z = np.zeros(10)
Z[4] = 1
print(Z)

(array([0, 1, 4], dtype=int64),)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [17]:
#Create a 8x8 matrix and fill it with a checkerboard pattern
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**np.ones()**

In [16]:
x = np.ones((3,2),dtype = int)
x

array([[1, 1],
       [1, 1],
       [1, 1]])

In [15]:
#Create a 2d array with 1 on the border and 0 inside
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


**Addition**

In [31]:
arr4 = np.array([[1,2],[3,4],[4,5]])
arr5 = np.array([[6,7],[8,9],[2,3]])
np.add(arr4,arr5)

array([[ 7,  9],
       [11, 13],
       [ 6,  8]])

**subtraction**

In [33]:
np.subtract(arr4,arr5)

array([[-5, -5],
       [-5, -5],
       [ 2,  2]])

**multiplication**

In [34]:
np.multiply(arr4,arr5)
# this is element vise multiplication.

array([[ 6, 14],
       [24, 36],
       [ 8, 15]])

**dot product**

In [17]:
arr6 = np.array([[1,2],[3,4]])
arr7 = np.array([[6,7],[8,9]])
np.dot(arr6,arr7)
#this is matrix multiplication.

array([[22, 25],
       [50, 57]])

In [18]:
arr8 = np.array([[1,2,3],[3,4,5]])
arr9 = np.array([[5,6,7],[8,9,7]])
np.dot(arr8,arr9)
# becoz arr8 is 2X3 matrix and arr9 is also 2X3 matrix but for matrix multiplication column of arr8 is equal to row of arr9.
# so either we have to use transpose function or reshape it.

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

**transpose**

In [44]:
np.transpose(arr4)
# interchange the row and column

array([[1, 3, 4],
       [2, 4, 5]])

In [21]:
arr9 = np.transpose(arr9)
arr9
#    OR
# arr9.reshape(3,2)

array([[5, 8],
       [6, 9],
       [7, 7]])

In [20]:
np.dot(arr8,arr9)

array([[38, 47],
       [74, 95]])

In [20]:
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(x+y)  
print(x-y)     
print(x*y)
print(x/y)

[[ 2  4  6]
 [ 6  8 10]]
[[0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [ 9 16 25]]
[[1. 1. 1.]
 [1. 1. 1.]]


**eye**

In [38]:
np.eye(2)
# this function gives a 2X2 identity matrix with default float values.

array([[1., 0.],
       [0., 1.]])

In [39]:
np.eye(3)
# 3X3 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**random**

In [47]:
a1 = np.random.randint(1,5,size = (2,2))
a1
#generate random integer values everytime between 1 to 5 of 2x2 size matrix

array([[3, 2],
       [3, 4]])

In [48]:
a1 = np.random.normal(1,5,size = (2,2))
a1
# by default generate float values

array([[ 5.03356319, -1.13694533],
       [-0.25531634,  2.47859806]])

In [9]:
#Create a 3x3x3 array with random values
Z = np.random.random((3,3,3))
print(Z)

[[[0.68252301 0.68187458 0.87958106]
  [0.81454494 0.56063594 0.12277859]
  [0.60443159 0.14614766 0.30570373]]

 [[0.01878746 0.4069791  0.81144804]
  [0.45506442 0.76264518 0.96095029]
  [0.37371691 0.8046413  0.75879212]]

 [[0.17607297 0.01211193 0.63864647]
  [0.38320551 0.61280033 0.78511828]
  [0.3019096  0.90774335 0.60512215]]]


**comparing memory occupied by list and numpy array**

In [17]:
import numpy as np
import sys
#memory occupied by list
s = range(1000)
print('memory occupied by List',sys.getsizeof(10)*len(s))
#memory occupied by numpy
d = np.arange(1000)
print('memory occupied by Numpy Array',d.size*d.itemsize)

memory occupied by List 28000
memory occupied by Numpy Array 4000


In [6]:
import time 
print(time.time())
# this is basically epox 

1594585655.0014346


**comparing speed of list and numpy array**

In [3]:
import time
size = 10000000
#checking list taken time
l1 = range(size)
l2 = range(size)
start = time.time()
result = [(x,y) for x,y in zip(l1,l2)]
print('Time taken by List:', time.time()-start)
#checking numpy array taken time
a1 = np.arange(size)
a2 = np.arange(size)
start2 = time.time()
result_numpy = a1+a2
print('Time taken by numpy:', time.time()-start2)

Time taken by List: 1.6606202125549316
Time taken by numpy: 0.03186178207397461


**slicing**

In [14]:
a = np.array([(1,2,3,4),(3,4,5,6)])
print(a)
print(a[0,2])

[[1 2 3 4]
 [3 4 5 6]]
3


In [15]:
a = np.array([(8,9),(10,11),(12,13)])
print(a[0:2,1])

[ 9 11]


**linespace**

In [16]:
#It has printed 10 values between 1 to 3
import numpy as np
a=np.linspace(1,3,10)
print(a)

[1.         1.22222222 1.44444444 1.66666667 1.88888889 2.11111111
 2.33333333 2.55555556 2.77777778 3.        ]


**max , min , sum , mean**

In [17]:
a= np.array([1,2,3])
print(a.min())
print(a.max())
print(a.sum())

1
3
6


In [13]:
#Create a 10x10 array with random values and find the minimum and maximum values
Z = np.random.random((10,10))
Zmin, Zmax= Z.min(), Z.max()
print(Zmin, Zmax)

0.002426278271872584 0.9900222999633174


axis = 0 is for rows and axis = 1 for columns

In [18]:
a = np.array([(1,2,3),(3,4,5)])
print(a)
print(a.sum(axis=1))

[[1 2 3]
 [3 4 5]]
[ 6 12]


In [14]:
#Create a random vector of size 30 and find the mean value
Z = np.random.random(30)
m = Z.mean()
print(m)

0.4975067306728143


**square root and standard deviation**

In [3]:
a = np.array([(1,2,3),(3,4,5)])

print(np.sqrt(a)) #square root
print(np.std(a))# standard deviation

# Standard Deviation=sqrt(mean(abs(x-x.mean( ))**2

[[1.         1.41421356 1.73205081]
 [1.73205081 2.         2.23606798]]
1.2909944487358056


**vertical and horizontal Stacking**

With hstack you can appened data horizontally and with vstack you can appened data vertically.

In [2]:
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])

print(np.vstack((x,y)))
print(np.hstack((x,y)))

# bydefault vertical stacking


[[1 2 3]
 [3 4 5]
 [1 2 3]
 [3 4 5]]
[[1 2 3 1 2 3]
 [3 4 5 3 4 5]]


In [22]:
a1 = np.arange(1,13)
a2 = np.arange(13,25)
print(np.stack((a1,a2)))
print(np.hstack((a1,a2)))
print(np.vstack((a1,a2)))
print(np.stack((a1,a2), axis = 1))

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]
[[ 1 13]
 [ 2 14]
 [ 3 15]
 [ 4 16]
 [ 5 17]
 [ 6 18]
 [ 7 19]
 [ 8 20]
 [ 9 21]
 [10 22]
 [11 23]
 [12 24]]


**ravel**

In [21]:
#ravel converts numpy array into single column
x= np.array([(1,2,3),(3,4,5)])
print(x.ravel())

[1 2 3 3 4 5]


**exponetial**

Python number method exp() returns returns exponential of x: e^x.

In [3]:
a= np.array([1,2,3])
print(np.exp(a))

[ 2.71828183  7.3890561  20.08553692]


**log**

log() is used to calculate the natural logarithm of x(x belongs to all the input array elements). It is the inverse of the exponential function as well as an element-wise natural logarithm.

In [4]:
a= np.array([1,2,3])
print(np.log(a))
print(np.log10(a))

[0.         0.69314718 1.09861229]
[0.         0.30103    0.47712125]


**np.diag**

The diag() function is used to extract a diagonal or construct a diagonal array.

In [16]:
#Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


**floor , ceil , astype , trunc**

In [19]:
#Extract the integer part of a random array using 5 different methods
Z = np.random.uniform(0,10,10)
print (Z -Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[6. 1. 6. 2. 9. 8. 2. 4. 2. 4.]
[6. 1. 6. 2. 9. 8. 2. 4. 2. 4.]
[6. 1. 6. 2. 9. 8. 2. 4. 2. 4.]
[6 1 6 2 9 8 2 4 2 4]
[6. 1. 6. 2. 9. 8. 2. 4. 2. 4.]


floor() function returns the floor value of the input array elements. The floor of a number x is i if i is the largest integer such that, i<=x.

ceil() function returns the ceil value of the input array elements. The floor of a number x is i if i is the smallest integer such that, i>=x.

trunc() function returns the truncated value of the input array elements. The truncated value t of input value x is the nearest integer which is closer to zero than x.The fractional part of the input number is discarded by this function.